baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
title = "Ming 的日常与笔记"
theme = "ananke"

[params]
  toc = true

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "日常"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "笔记"
  url = "/notes/"
  weight = 2

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 3

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 4
